version: 2

models:
  - name: customers 
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    columns:
      - name: customer_id 
        tests:
          - unique
          - not_null
          
  - name: stg_orders
    columns:
      - name: order_id   
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted values:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
         
      - name: customer_id 
        tests:
          - not null
          - relationships:
             to: ref('stg_customers')
             field: customer_id